In [1]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

NameError: name 'tf' is not defined

In [2]:
import tensorflow as tf

In [3]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

In [4]:
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))

[[ 0.46256042  3.29166651  2.70714283]
 [ 0.75780451  2.64809012  0.16051292]]
[[-1.8260324  -3.94231176 -0.89970911]
 [-4.0429945   3.21951389 -6.70760775]]


In [5]:
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)
print(sess.run(shuff))
print(sess.run(shuff))

[[5 6]
 [1 2]
 [3 4]]
[[3 4]
 [5 6]
 [1 2]]


In [6]:
norm = tf.random_normal([2, 3], seed=1234)
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))

[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]]
[[ 0.96462417  0.34291974  0.24251089]
 [ 1.05785966  1.65749764  0.82108968]]
[[ 0.51340485 -0.25581399  0.65199131]
 [ 1.39236379  0.37256798  0.20336303]]
[[ 0.96462417  0.34291974  0.24251089]
 [ 1.05785966  1.65749764  0.82108968]]


In [7]:
a = tf.random_uniform([1])
b = tf.random_normal([1])

print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A3'
  print(sess2.run(a))  # generates 'A4'
  print(sess2.run(b))  # generates 'B3'
  print(sess2.run(b))  # generates 'B4'

Session 1
[ 0.30346096]
[ 0.79920781]
[ 0.19583587]
[ 0.26705405]
Session 2
[ 0.16695356]
[ 0.17594051]
[ 0.1404324]
[-1.38750505]


In [8]:
a = tf.random_uniform([1], seed=1)
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate the same
# sequence of values for 'a', but different sequences of values for 'b'.
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B3'
  print(sess2.run(b))  # generates 'B4'

Session 1
[ 0.23903739]
[ 0.22267115]
[ 0.48155633]
[ 1.2638731]
Session 2
[ 0.23903739]
[ 0.22267115]
[ 1.44809365]
[-0.14793627]


In [9]:
tf.set_random_seed(1234)
a = tf.random_uniform([1])
b = tf.random_normal([1])

# Repeatedly running this block with the same graph will generate the same
# sequences of 'a' and 'b'.
print("Session 1")
with tf.Session() as sess1:
  print(sess1.run(a))  # generates 'A1'
  print(sess1.run(a))  # generates 'A2'
  print(sess1.run(b))  # generates 'B1'
  print(sess1.run(b))  # generates 'B2'

print("Session 2")
with tf.Session() as sess2:
  print(sess2.run(a))  # generates 'A1'
  print(sess2.run(a))  # generates 'A2'
  print(sess2.run(b))  # generates 'B1'
  print(sess2.run(b))  # generates 'B2'

Session 1
[ 0.01245928]
[ 0.6278342]
[-0.46333826]
[-0.03163962]
Session 2
[ 0.01245928]
[ 0.6278342]
[-0.46333826]
[-0.03163962]


In [16]:
import math
IMAGE_PIXELS = 2
hidden1_units = 3
a = tf.truncated_normal([IMAGE_PIXELS, hidden1_units],
                        stddev=1.0 / math.sqrt(float(IMAGE_PIXELS)))
with tf.Session() as sess2:
    print(sess2.run(a))

[[-0.59190488 -0.08987984  0.59282303]
 [ 0.51827449 -0.75389862 -0.21751149]]


In [17]:
labels = tf.to_int64(labels)

NameError: name 'labels' is not defined

In [20]:
import matplotlib.pyplot as plt

n = 500000
A = tf.truncated_normal((n,))
B = tf.random_normal((n,))
with tf.Session() as sess:
    a, b = sess.run([A, B])

ImportError: No module named 'matplotlib'